#!/bin/sh

ADDONNAME=feeder-button
ADDON_DIR=/usr/local/addons/feeder-button
PROFILE_DIR=/usr/local/etc/profile.d
WWW_DIR=/usr/local/etc/config/addons/www/feeder-button


case "$1" in
""|start)
  ;;
info)
  echo "Info: <b>feeder button CCU Addon</b><br>"
  

  echo "Info: <br>"
  echo "Info: (c) 2018 Holger Imbery<br>"
  echo "Info: <a href='https://github.com/holgerimbery/feeder'>https://github.com/holgerimbery/feeder</a>"
  echo "Version: $(cat ${ADDON_DIR}/VERSION)"
  echo "Name: feeder-button<br>"
  echo "Update: /addons/update-check.cgi"
  echo "Config-Url: /addons/feeder-button/index.cgi"
  echo "Operations: uninstall"
  ;;
uninstall)
  rm -rf $ADDON_DIR
  rm -rf $WWW_DIR
  rm -rf $PROFILE_DIR/feeder-button-addons.sh
  
  ;;
esac

exit 0

