#!/bin/sh
ADDONDIR=/usr/local/addons/feeder-button
while read var value
do
    export "$var"="$value"
done < /usr/local/addons/feeder-button/host.conf

URL=$HOST
echo $URL
sed 's/##awesome_URL##/'$URL'/g' <$ADDONDIR/feeder.cfg.template > $ADDONDIR/feeder.cfg
/usr/local/addons/feeder-button/update_addon feeder /usr/local/addons/feeder-button/feeder.cfg


