#!/bin/sh

ADDON_NAME=feeder-button
CONFIG_DIR=/usr/local/etc/config
WWW_DIR=/usr/local/etc/config/addons/www/hm-tools
ADDON_DIR=/usr/local/addons/${ADDON_NAME}
PROFILE_DIR=/usr/local/etc/profile.d
RCD_DIR=${CONFIG_DIR}/rc.d

# make sure this addon is only executed on
# supported platforms

if [ "$1" == "HM-RASPBERRYMATIC" ]; then

  mount | grep /usr/local 2>&1 >/dev/null
    if [ $? -eq 1 ]; then
      mount /usr/local
    fi

  # create necessary directories
  mkdir -p ${ADDON_DIR}
  chmod 755 ${ADDON_DIR}
  # web-configuration
  mkdir -p ${WWW_DIR}
  chmod 755 ${WWW_DIR}
  # rc.d
  mkdir -p ${RCD_DIR}
  chmod 755 ${RCD_DIR}
  # profile.d
  mkdir -p ${PROFILE_DIR}
  chmod 755 ${PROFILE_DIR}


  # remove old stuff
  rm -rf $ADDON_DIR/*

  # copy profile.d
  cp -af profile.d/* ${PROFILE_DIR}/


  # copy web-configuration
  cp -af www/* ${WWW_DIR}

  # copy version
  cp -af VERSION ${ADDON_DIR}/

  # copy startup script
  cp -af rc.d/* ${RCD_DIR}

  #build system launcher
  chmod +x ${RCD_DIR}/${ADDON_NAME}
  
  cp -af update_addon ${ADDON_DIR}/
  cp -af update_cfg ${ADDON_DIR}/
  cp -af *.cfg ${ADDON_DIR}/
  cp -af *.cfg.template ${ADDON_DIR}/
  chmod 755 ${ADDON_DIR}/update_addon
  chmod 755 ${ADDON_DIR}/update_cfg
fi

./update_addon node-red
./update_addon node-red-dashboard

#
#   Create Buttons in Homematic WebUI
#
touch $CONF_DIR/hm_addons.cfg
./update_addon nodered nodered.cfg
./update_addon nrdash nrdash.cfg
./update_addon feeder feeder.cfg
./update_addon chronograf chronograf.cfg

# synchronize filesystem before performing a reboot
# afterwards
sync
